package com.xianyo.util.commentmodule.dao.mapper;

import com.xianyo.util.commentmodule.dao.pojo.CommentData;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(CommentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(CommentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Long commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(CommentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(CommentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<CommentData> selectByExample(CommentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    CommentData selectByPrimaryKey(Long commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") CommentData record, @Param("example") CommentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") CommentData record, @Param("example") CommentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(CommentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(CommentData record);
}