package com.project.dao;

import com.project.model.AdministratorData;
import com.project.model.AdministratorDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministratorDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(AdministratorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(AdministratorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(AdministratorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(AdministratorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<AdministratorData> selectByExample(AdministratorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    AdministratorData selectByPrimaryKey(Long adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") AdministratorData record, @Param("example") AdministratorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") AdministratorData record, @Param("example") AdministratorDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(AdministratorData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administratorinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(AdministratorData record);
}