package com.project.dao;

import com.project.model.AlReadComplaintData;
import com.project.model.AlReadComplaintDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlReadComplaintDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(AlReadComplaintDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(AlReadComplaintDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(AlReadComplaintData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(AlReadComplaintData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<AlReadComplaintData> selectByExample(AlReadComplaintDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") AlReadComplaintData record, @Param("example") AlReadComplaintDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alreadcomplaintinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") AlReadComplaintData record, @Param("example") AlReadComplaintDataExample example);
}