package com.project.dao;

import com.project.model.EmojData;
import com.project.model.EmojDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmojDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(EmojDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(EmojDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(EmojData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(EmojData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<EmojData> selectByExample(EmojDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") EmojData record, @Param("example") EmojDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emojinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") EmojData record, @Param("example") EmojDataExample example);
}