package com.project.dao;

import com.project.model.QuesScenicRelationData;
import com.project.model.QuesScenicRelationDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuesScenicRelationDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(QuesScenicRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(QuesScenicRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(QuesScenicRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(QuesScenicRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<QuesScenicRelationData> selectByExample(QuesScenicRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") QuesScenicRelationData record, @Param("example") QuesScenicRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table quesscenrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") QuesScenicRelationData record, @Param("example") QuesScenicRelationDataExample example);
}