package com.project.dao;

import com.project.model.QuestionData;
import com.project.model.QuestionDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(QuestionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(QuestionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Long questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(QuestionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(QuestionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<QuestionData> selectByExample(QuestionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    QuestionData selectByPrimaryKey(Long questionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") QuestionData record, @Param("example") QuestionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") QuestionData record, @Param("example") QuestionDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(QuestionData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(QuestionData record);
}