package com.project.dao;

import com.project.model.SensitiveData;
import com.project.model.SensitiveDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensitiveDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(SensitiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(SensitiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(SensitiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(SensitiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<SensitiveData> selectByExample(SensitiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    SensitiveData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") SensitiveData record, @Param("example") SensitiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") SensitiveData record, @Param("example") SensitiveDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(SensitiveData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitiveinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(SensitiveData record);
}