package com.project.dao;

import com.project.model.TravelnoteData;
import com.project.model.TravelnoteDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelnoteDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(TravelnoteDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(TravelnoteDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Long travelnoteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(TravelnoteData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(TravelnoteData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<TravelnoteData> selectByExample(TravelnoteDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    TravelnoteData selectByPrimaryKey(Long travelnoteid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TravelnoteData record, @Param("example") TravelnoteDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") TravelnoteData record, @Param("example") TravelnoteDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(TravelnoteData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnoteinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(TravelnoteData record);
}