package com.project.dao;

import com.project.model.TravelnoteCollectData;
import com.project.model.TravelnoteCollectDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TravelnoteCollectDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(TravelnoteCollectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(TravelnoteCollectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(TravelnoteCollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(TravelnoteCollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<TravelnoteCollectData> selectByExample(TravelnoteCollectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    TravelnoteCollectData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") TravelnoteCollectData record, @Param("example") TravelnoteCollectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") TravelnoteCollectData record, @Param("example") TravelnoteCollectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(TravelnoteCollectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travelnotecollect_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(TravelnoteCollectData record);
}