package com.project.dao;

import com.project.model.UserData;
import com.project.model.UserDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<UserData> selectByExample(UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    UserData selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") UserData record, @Param("example") UserDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKeySelective(UserData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByPrimaryKey(UserData record);
}