package com.project.dao;

import com.project.model.UserTagRelationData;
import com.project.model.UserTagRelationDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTagRelationDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int countByExample(UserTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int deleteByExample(UserTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insert(UserTagRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int insertSelective(UserTagRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    List<UserTagRelationData> selectByExample(UserTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserTagRelationData record, @Param("example") UserTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usertagrelation_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    int updateByExample(@Param("record") UserTagRelationData record, @Param("example") UserTagRelationDataExample example);
}