package com.xianyo.util.commentmodule.dao.pojo;

import java.util.Date;

public class CommentData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.commentID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.commentUserID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long commentuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.comment
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.commentTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Date commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer praisetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.replyID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long replyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double joy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double sad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double fear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double anger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double disgust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double surprise;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.commentID
     *
     * @return the value of commentinfo_.commentID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.commentID
     *
     * @param commentid the value for commentinfo_.commentID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.userID
     *
     * @return the value of commentinfo_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.userID
     *
     * @param userid the value for commentinfo_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.commentUserID
     *
     * @return the value of commentinfo_.commentUserID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getCommentuserid() {
        return commentuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.commentUserID
     *
     * @param commentuserid the value for commentinfo_.commentUserID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCommentuserid(Long commentuserid) {
        this.commentuserid = commentuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.scenicID
     *
     * @return the value of commentinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.scenicID
     *
     * @param scenicid the value for commentinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.comment
     *
     * @return the value of commentinfo_.comment
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.comment
     *
     * @param comment the value for commentinfo_.comment
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.commentTime
     *
     * @return the value of commentinfo_.commentTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.commentTime
     *
     * @param commenttime the value for commentinfo_.commentTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.praiseTime
     *
     * @return the value of commentinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getPraisetime() {
        return praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.praiseTime
     *
     * @param praisetime the value for commentinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPraisetime(Integer praisetime) {
        this.praisetime = praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.replyID
     *
     * @return the value of commentinfo_.replyID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.replyID
     *
     * @param replyid the value for commentinfo_.replyID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setReplyid(Long replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.joy
     *
     * @return the value of commentinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getJoy() {
        return joy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.joy
     *
     * @param joy the value for commentinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setJoy(Double joy) {
        this.joy = joy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.sad
     *
     * @return the value of commentinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getSad() {
        return sad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.sad
     *
     * @param sad the value for commentinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSad(Double sad) {
        this.sad = sad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.fear
     *
     * @return the value of commentinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getFear() {
        return fear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.fear
     *
     * @param fear the value for commentinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setFear(Double fear) {
        this.fear = fear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.anger
     *
     * @return the value of commentinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getAnger() {
        return anger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.anger
     *
     * @param anger the value for commentinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAnger(Double anger) {
        this.anger = anger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.disgust
     *
     * @return the value of commentinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getDisgust() {
        return disgust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.disgust
     *
     * @param disgust the value for commentinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDisgust(Double disgust) {
        this.disgust = disgust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo_.surprise
     *
     * @return the value of commentinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getSurprise() {
        return surprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo_.surprise
     *
     * @param surprise the value for commentinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSurprise(Double surprise) {
        this.surprise = surprise;
    }
}