package com.project.model;

public class AnswerCollectData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answercollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answercollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answercollect_.answerID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long answerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answercollect_.id
     *
     * @return the value of answercollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answercollect_.id
     *
     * @param id the value for answercollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answercollect_.userID
     *
     * @return the value of answercollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answercollect_.userID
     *
     * @param userid the value for answercollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answercollect_.answerID
     *
     * @return the value of answercollect_.answerID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answercollect_.answerID
     *
     * @param answerid the value for answercollect_.answerID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAnswerid(Long answerid) {
        this.answerid = answerid;
    }
}