package com.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AnswerDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public AnswerDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnsweridIsNull() {
            addCriterion("answerID is null");
            return (Criteria) this;
        }

        public Criteria andAnsweridIsNotNull() {
            addCriterion("answerID is not null");
            return (Criteria) this;
        }

        public Criteria andAnsweridEqualTo(Long value) {
            addCriterion("answerID =", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridNotEqualTo(Long value) {
            addCriterion("answerID <>", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridGreaterThan(Long value) {
            addCriterion("answerID >", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridGreaterThanOrEqualTo(Long value) {
            addCriterion("answerID >=", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridLessThan(Long value) {
            addCriterion("answerID <", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridLessThanOrEqualTo(Long value) {
            addCriterion("answerID <=", value, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridIn(List<Long> values) {
            addCriterion("answerID in", values, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridNotIn(List<Long> values) {
            addCriterion("answerID not in", values, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridBetween(Long value1, Long value2) {
            addCriterion("answerID between", value1, value2, "answerid");
            return (Criteria) this;
        }

        public Criteria andAnsweridNotBetween(Long value1, Long value2) {
            addCriterion("answerID not between", value1, value2, "answerid");
            return (Criteria) this;
        }

        public Criteria andQuestionidIsNull() {
            addCriterion("questionID is null");
            return (Criteria) this;
        }

        public Criteria andQuestionidIsNotNull() {
            addCriterion("questionID is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionidEqualTo(Long value) {
            addCriterion("questionID =", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotEqualTo(Long value) {
            addCriterion("questionID <>", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThan(Long value) {
            addCriterion("questionID >", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThanOrEqualTo(Long value) {
            addCriterion("questionID >=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThan(Long value) {
            addCriterion("questionID <", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThanOrEqualTo(Long value) {
            addCriterion("questionID <=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidIn(List<Long> values) {
            addCriterion("questionID in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotIn(List<Long> values) {
            addCriterion("questionID not in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidBetween(Long value1, Long value2) {
            addCriterion("questionID between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotBetween(Long value1, Long value2) {
            addCriterion("questionID not between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andSolveridIsNull() {
            addCriterion("solverID is null");
            return (Criteria) this;
        }

        public Criteria andSolveridIsNotNull() {
            addCriterion("solverID is not null");
            return (Criteria) this;
        }

        public Criteria andSolveridEqualTo(Long value) {
            addCriterion("solverID =", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridNotEqualTo(Long value) {
            addCriterion("solverID <>", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridGreaterThan(Long value) {
            addCriterion("solverID >", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridGreaterThanOrEqualTo(Long value) {
            addCriterion("solverID >=", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridLessThan(Long value) {
            addCriterion("solverID <", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridLessThanOrEqualTo(Long value) {
            addCriterion("solverID <=", value, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridIn(List<Long> values) {
            addCriterion("solverID in", values, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridNotIn(List<Long> values) {
            addCriterion("solverID not in", values, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridBetween(Long value1, Long value2) {
            addCriterion("solverID between", value1, value2, "solverid");
            return (Criteria) this;
        }

        public Criteria andSolveridNotBetween(Long value1, Long value2) {
            addCriterion("solverID not between", value1, value2, "solverid");
            return (Criteria) this;
        }

        public Criteria andAnswercontentIsNull() {
            addCriterion("answerContent is null");
            return (Criteria) this;
        }

        public Criteria andAnswercontentIsNotNull() {
            addCriterion("answerContent is not null");
            return (Criteria) this;
        }

        public Criteria andAnswercontentEqualTo(String value) {
            addCriterion("answerContent =", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentNotEqualTo(String value) {
            addCriterion("answerContent <>", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentGreaterThan(String value) {
            addCriterion("answerContent >", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentGreaterThanOrEqualTo(String value) {
            addCriterion("answerContent >=", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentLessThan(String value) {
            addCriterion("answerContent <", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentLessThanOrEqualTo(String value) {
            addCriterion("answerContent <=", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentLike(String value) {
            addCriterion("answerContent like", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentNotLike(String value) {
            addCriterion("answerContent not like", value, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentIn(List<String> values) {
            addCriterion("answerContent in", values, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentNotIn(List<String> values) {
            addCriterion("answerContent not in", values, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentBetween(String value1, String value2) {
            addCriterion("answerContent between", value1, value2, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswercontentNotBetween(String value1, String value2) {
            addCriterion("answerContent not between", value1, value2, "answercontent");
            return (Criteria) this;
        }

        public Criteria andAnswerdateIsNull() {
            addCriterion("answerDate is null");
            return (Criteria) this;
        }

        public Criteria andAnswerdateIsNotNull() {
            addCriterion("answerDate is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerdateEqualTo(Date value) {
            addCriterion("answerDate =", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateNotEqualTo(Date value) {
            addCriterion("answerDate <>", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateGreaterThan(Date value) {
            addCriterion("answerDate >", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateGreaterThanOrEqualTo(Date value) {
            addCriterion("answerDate >=", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateLessThan(Date value) {
            addCriterion("answerDate <", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateLessThanOrEqualTo(Date value) {
            addCriterion("answerDate <=", value, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateIn(List<Date> values) {
            addCriterion("answerDate in", values, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateNotIn(List<Date> values) {
            addCriterion("answerDate not in", values, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateBetween(Date value1, Date value2) {
            addCriterion("answerDate between", value1, value2, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerdateNotBetween(Date value1, Date value2) {
            addCriterion("answerDate not between", value1, value2, "answerdate");
            return (Criteria) this;
        }

        public Criteria andAnswerpvIsNull() {
            addCriterion("answerPV is null");
            return (Criteria) this;
        }

        public Criteria andAnswerpvIsNotNull() {
            addCriterion("answerPV is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerpvEqualTo(Integer value) {
            addCriterion("answerPV =", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvNotEqualTo(Integer value) {
            addCriterion("answerPV <>", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvGreaterThan(Integer value) {
            addCriterion("answerPV >", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvGreaterThanOrEqualTo(Integer value) {
            addCriterion("answerPV >=", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvLessThan(Integer value) {
            addCriterion("answerPV <", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvLessThanOrEqualTo(Integer value) {
            addCriterion("answerPV <=", value, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvIn(List<Integer> values) {
            addCriterion("answerPV in", values, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvNotIn(List<Integer> values) {
            addCriterion("answerPV not in", values, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvBetween(Integer value1, Integer value2) {
            addCriterion("answerPV between", value1, value2, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswerpvNotBetween(Integer value1, Integer value2) {
            addCriterion("answerPV not between", value1, value2, "answerpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvIsNull() {
            addCriterion("answerValidPV is null");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvIsNotNull() {
            addCriterion("answerValidPV is not null");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvEqualTo(Integer value) {
            addCriterion("answerValidPV =", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvNotEqualTo(Integer value) {
            addCriterion("answerValidPV <>", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvGreaterThan(Integer value) {
            addCriterion("answerValidPV >", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvGreaterThanOrEqualTo(Integer value) {
            addCriterion("answerValidPV >=", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvLessThan(Integer value) {
            addCriterion("answerValidPV <", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvLessThanOrEqualTo(Integer value) {
            addCriterion("answerValidPV <=", value, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvIn(List<Integer> values) {
            addCriterion("answerValidPV in", values, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvNotIn(List<Integer> values) {
            addCriterion("answerValidPV not in", values, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvBetween(Integer value1, Integer value2) {
            addCriterion("answerValidPV between", value1, value2, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswervalidpvNotBetween(Integer value1, Integer value2) {
            addCriterion("answerValidPV not between", value1, value2, "answervalidpv");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIsNull() {
            addCriterion("answerUrl is null");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIsNotNull() {
            addCriterion("answerUrl is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerurlEqualTo(String value) {
            addCriterion("answerUrl =", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotEqualTo(String value) {
            addCriterion("answerUrl <>", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlGreaterThan(String value) {
            addCriterion("answerUrl >", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlGreaterThanOrEqualTo(String value) {
            addCriterion("answerUrl >=", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLessThan(String value) {
            addCriterion("answerUrl <", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLessThanOrEqualTo(String value) {
            addCriterion("answerUrl <=", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlLike(String value) {
            addCriterion("answerUrl like", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotLike(String value) {
            addCriterion("answerUrl not like", value, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlIn(List<String> values) {
            addCriterion("answerUrl in", values, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotIn(List<String> values) {
            addCriterion("answerUrl not in", values, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlBetween(String value1, String value2) {
            addCriterion("answerUrl between", value1, value2, "answerurl");
            return (Criteria) this;
        }

        public Criteria andAnswerurlNotBetween(String value1, String value2) {
            addCriterion("answerUrl not between", value1, value2, "answerurl");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIsNull() {
            addCriterion("praiseTime is null");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIsNotNull() {
            addCriterion("praiseTime is not null");
            return (Criteria) this;
        }

        public Criteria andPraisetimeEqualTo(Integer value) {
            addCriterion("praiseTime =", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotEqualTo(Integer value) {
            addCriterion("praiseTime <>", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeGreaterThan(Integer value) {
            addCriterion("praiseTime >", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("praiseTime >=", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeLessThan(Integer value) {
            addCriterion("praiseTime <", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeLessThanOrEqualTo(Integer value) {
            addCriterion("praiseTime <=", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIn(List<Integer> values) {
            addCriterion("praiseTime in", values, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotIn(List<Integer> values) {
            addCriterion("praiseTime not in", values, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeBetween(Integer value1, Integer value2) {
            addCriterion("praiseTime between", value1, value2, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("praiseTime not between", value1, value2, "praisetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answerinfo_
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table answerinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}