package com.project.model;

public class AroundScenicSpotData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aroundsenicspotinfo_.surroundNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer surroundnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aroundsenicspotinfo_.scenicScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double scenicscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aroundsenicspotinfo_.commentNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer commentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aroundsenicspotinfo_.questionNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer questionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aroundsenicspotinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long scenicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aroundsenicspotinfo_.surroundNum
     *
     * @return the value of aroundsenicspotinfo_.surroundNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getSurroundnum() {
        return surroundnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aroundsenicspotinfo_.surroundNum
     *
     * @param surroundnum the value for aroundsenicspotinfo_.surroundNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSurroundnum(Integer surroundnum) {
        this.surroundnum = surroundnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aroundsenicspotinfo_.scenicScore
     *
     * @return the value of aroundsenicspotinfo_.scenicScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getScenicscore() {
        return scenicscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aroundsenicspotinfo_.scenicScore
     *
     * @param scenicscore the value for aroundsenicspotinfo_.scenicScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicscore(Double scenicscore) {
        this.scenicscore = scenicscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aroundsenicspotinfo_.commentNum
     *
     * @return the value of aroundsenicspotinfo_.commentNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aroundsenicspotinfo_.commentNum
     *
     * @param commentnum the value for aroundsenicspotinfo_.commentNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aroundsenicspotinfo_.questionNum
     *
     * @return the value of aroundsenicspotinfo_.questionNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getQuestionnum() {
        return questionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aroundsenicspotinfo_.questionNum
     *
     * @param questionnum the value for aroundsenicspotinfo_.questionNum
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionnum(Integer questionnum) {
        this.questionnum = questionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aroundsenicspotinfo_.scenicID
     *
     * @return the value of aroundsenicspotinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aroundsenicspotinfo_.scenicID
     *
     * @param scenicid the value for aroundsenicspotinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }
}