package com.project.model;

public class EmojData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.word
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.wordtype
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer wordtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double joy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double sad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double fear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double anger;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double disgust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emojinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Double surprise;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.word
     *
     * @return the value of emojinfo_.word
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.word
     *
     * @param word the value for emojinfo_.word
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.wordtype
     *
     * @return the value of emojinfo_.wordtype
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getWordtype() {
        return wordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.wordtype
     *
     * @param wordtype the value for emojinfo_.wordtype
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setWordtype(Integer wordtype) {
        this.wordtype = wordtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.joy
     *
     * @return the value of emojinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getJoy() {
        return joy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.joy
     *
     * @param joy the value for emojinfo_.joy
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setJoy(Double joy) {
        this.joy = joy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.sad
     *
     * @return the value of emojinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getSad() {
        return sad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.sad
     *
     * @param sad the value for emojinfo_.sad
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSad(Double sad) {
        this.sad = sad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.fear
     *
     * @return the value of emojinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getFear() {
        return fear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.fear
     *
     * @param fear the value for emojinfo_.fear
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setFear(Double fear) {
        this.fear = fear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.anger
     *
     * @return the value of emojinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getAnger() {
        return anger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.anger
     *
     * @param anger the value for emojinfo_.anger
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAnger(Double anger) {
        this.anger = anger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.disgust
     *
     * @return the value of emojinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getDisgust() {
        return disgust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.disgust
     *
     * @param disgust the value for emojinfo_.disgust
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDisgust(Double disgust) {
        this.disgust = disgust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emojinfo_.surprise
     *
     * @return the value of emojinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Double getSurprise() {
        return surprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emojinfo_.surprise
     *
     * @param surprise the value for emojinfo_.surprise
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSurprise(Double surprise) {
        this.surprise = surprise;
    }
}