package com.project.model;

import java.util.Date;

public class MicroblogData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.microblogID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long microblogid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.context
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.pictureDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String picturedir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer collecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer readtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer praisetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer complainttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String microblogurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microbloginfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.microblogID
     *
     * @return the value of microbloginfo_.microblogID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getMicroblogid() {
        return microblogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.microblogID
     *
     * @param microblogid the value for microbloginfo_.microblogID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setMicroblogid(Long microblogid) {
        this.microblogid = microblogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.authorID
     *
     * @return the value of microbloginfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.authorID
     *
     * @param authorid the value for microbloginfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAuthorid(Long authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.publishTime
     *
     * @return the value of microbloginfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.publishTime
     *
     * @param publishtime the value for microbloginfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.context
     *
     * @return the value of microbloginfo_.context
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.context
     *
     * @param context the value for microbloginfo_.context
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.pictureDir
     *
     * @return the value of microbloginfo_.pictureDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getPicturedir() {
        return picturedir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.pictureDir
     *
     * @param picturedir the value for microbloginfo_.pictureDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPicturedir(String picturedir) {
        this.picturedir = picturedir == null ? null : picturedir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.collectTime
     *
     * @return the value of microbloginfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getCollecttime() {
        return collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.collectTime
     *
     * @param collecttime the value for microbloginfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCollecttime(Integer collecttime) {
        this.collecttime = collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.readTime
     *
     * @return the value of microbloginfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.readTime
     *
     * @param readtime the value for microbloginfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setReadtime(Integer readtime) {
        this.readtime = readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.praiseTime
     *
     * @return the value of microbloginfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getPraisetime() {
        return praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.praiseTime
     *
     * @param praisetime the value for microbloginfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPraisetime(Integer praisetime) {
        this.praisetime = praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.complaintTime
     *
     * @return the value of microbloginfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getComplainttime() {
        return complainttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.complaintTime
     *
     * @param complainttime the value for microbloginfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setComplainttime(Integer complainttime) {
        this.complainttime = complainttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.microblogUrl
     *
     * @return the value of microbloginfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getMicroblogurl() {
        return microblogurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.microblogUrl
     *
     * @param microblogurl the value for microbloginfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setMicroblogurl(String microblogurl) {
        this.microblogurl = microblogurl == null ? null : microblogurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microbloginfo_.state
     *
     * @return the value of microbloginfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microbloginfo_.state
     *
     * @param state the value for microbloginfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}