package com.project.model;

public class MicroTagRelationData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microtagrelation_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column microtagrelation_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microtagrelation_.tagID
     *
     * @return the value of microtagrelation_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microtagrelation_.tagID
     *
     * @param tagid the value for microtagrelation_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTagid(Long tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column microtagrelation_.userid
     *
     * @return the value of microtagrelation_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column microtagrelation_.userid
     *
     * @param userid the value for microtagrelation_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}