package com.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MicroblogDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public MicroblogDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMicroblogidIsNull() {
            addCriterion("microblogID is null");
            return (Criteria) this;
        }

        public Criteria andMicroblogidIsNotNull() {
            addCriterion("microblogID is not null");
            return (Criteria) this;
        }

        public Criteria andMicroblogidEqualTo(Long value) {
            addCriterion("microblogID =", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidNotEqualTo(Long value) {
            addCriterion("microblogID <>", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidGreaterThan(Long value) {
            addCriterion("microblogID >", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidGreaterThanOrEqualTo(Long value) {
            addCriterion("microblogID >=", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidLessThan(Long value) {
            addCriterion("microblogID <", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidLessThanOrEqualTo(Long value) {
            addCriterion("microblogID <=", value, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidIn(List<Long> values) {
            addCriterion("microblogID in", values, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidNotIn(List<Long> values) {
            addCriterion("microblogID not in", values, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidBetween(Long value1, Long value2) {
            addCriterion("microblogID between", value1, value2, "microblogid");
            return (Criteria) this;
        }

        public Criteria andMicroblogidNotBetween(Long value1, Long value2) {
            addCriterion("microblogID not between", value1, value2, "microblogid");
            return (Criteria) this;
        }

        public Criteria andAuthoridIsNull() {
            addCriterion("authorID is null");
            return (Criteria) this;
        }

        public Criteria andAuthoridIsNotNull() {
            addCriterion("authorID is not null");
            return (Criteria) this;
        }

        public Criteria andAuthoridEqualTo(Long value) {
            addCriterion("authorID =", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridNotEqualTo(Long value) {
            addCriterion("authorID <>", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridGreaterThan(Long value) {
            addCriterion("authorID >", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridGreaterThanOrEqualTo(Long value) {
            addCriterion("authorID >=", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridLessThan(Long value) {
            addCriterion("authorID <", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridLessThanOrEqualTo(Long value) {
            addCriterion("authorID <=", value, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridIn(List<Long> values) {
            addCriterion("authorID in", values, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridNotIn(List<Long> values) {
            addCriterion("authorID not in", values, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridBetween(Long value1, Long value2) {
            addCriterion("authorID between", value1, value2, "authorid");
            return (Criteria) this;
        }

        public Criteria andAuthoridNotBetween(Long value1, Long value2) {
            addCriterion("authorID not between", value1, value2, "authorid");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNull() {
            addCriterion("publishTime is null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIsNotNull() {
            addCriterion("publishTime is not null");
            return (Criteria) this;
        }

        public Criteria andPublishtimeEqualTo(Date value) {
            addCriterion("publishTime =", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotEqualTo(Date value) {
            addCriterion("publishTime <>", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThan(Date value) {
            addCriterion("publishTime >", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("publishTime >=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThan(Date value) {
            addCriterion("publishTime <", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeLessThanOrEqualTo(Date value) {
            addCriterion("publishTime <=", value, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeIn(List<Date> values) {
            addCriterion("publishTime in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotIn(List<Date> values) {
            addCriterion("publishTime not in", values, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeBetween(Date value1, Date value2) {
            addCriterion("publishTime between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andPublishtimeNotBetween(Date value1, Date value2) {
            addCriterion("publishTime not between", value1, value2, "publishtime");
            return (Criteria) this;
        }

        public Criteria andContextIsNull() {
            addCriterion("context is null");
            return (Criteria) this;
        }

        public Criteria andContextIsNotNull() {
            addCriterion("context is not null");
            return (Criteria) this;
        }

        public Criteria andContextEqualTo(String value) {
            addCriterion("context =", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextNotEqualTo(String value) {
            addCriterion("context <>", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextGreaterThan(String value) {
            addCriterion("context >", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextGreaterThanOrEqualTo(String value) {
            addCriterion("context >=", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextLessThan(String value) {
            addCriterion("context <", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextLessThanOrEqualTo(String value) {
            addCriterion("context <=", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextLike(String value) {
            addCriterion("context like", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextNotLike(String value) {
            addCriterion("context not like", value, "context");
            return (Criteria) this;
        }

        public Criteria andContextIn(List<String> values) {
            addCriterion("context in", values, "context");
            return (Criteria) this;
        }

        public Criteria andContextNotIn(List<String> values) {
            addCriterion("context not in", values, "context");
            return (Criteria) this;
        }

        public Criteria andContextBetween(String value1, String value2) {
            addCriterion("context between", value1, value2, "context");
            return (Criteria) this;
        }

        public Criteria andContextNotBetween(String value1, String value2) {
            addCriterion("context not between", value1, value2, "context");
            return (Criteria) this;
        }

        public Criteria andPicturedirIsNull() {
            addCriterion("pictureDir is null");
            return (Criteria) this;
        }

        public Criteria andPicturedirIsNotNull() {
            addCriterion("pictureDir is not null");
            return (Criteria) this;
        }

        public Criteria andPicturedirEqualTo(String value) {
            addCriterion("pictureDir =", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotEqualTo(String value) {
            addCriterion("pictureDir <>", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirGreaterThan(String value) {
            addCriterion("pictureDir >", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirGreaterThanOrEqualTo(String value) {
            addCriterion("pictureDir >=", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLessThan(String value) {
            addCriterion("pictureDir <", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLessThanOrEqualTo(String value) {
            addCriterion("pictureDir <=", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLike(String value) {
            addCriterion("pictureDir like", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotLike(String value) {
            addCriterion("pictureDir not like", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirIn(List<String> values) {
            addCriterion("pictureDir in", values, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotIn(List<String> values) {
            addCriterion("pictureDir not in", values, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirBetween(String value1, String value2) {
            addCriterion("pictureDir between", value1, value2, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotBetween(String value1, String value2) {
            addCriterion("pictureDir not between", value1, value2, "picturedir");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIsNull() {
            addCriterion("collectTime is null");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIsNotNull() {
            addCriterion("collectTime is not null");
            return (Criteria) this;
        }

        public Criteria andCollecttimeEqualTo(Integer value) {
            addCriterion("collectTime =", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotEqualTo(Integer value) {
            addCriterion("collectTime <>", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeGreaterThan(Integer value) {
            addCriterion("collectTime >", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("collectTime >=", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeLessThan(Integer value) {
            addCriterion("collectTime <", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeLessThanOrEqualTo(Integer value) {
            addCriterion("collectTime <=", value, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeIn(List<Integer> values) {
            addCriterion("collectTime in", values, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotIn(List<Integer> values) {
            addCriterion("collectTime not in", values, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeBetween(Integer value1, Integer value2) {
            addCriterion("collectTime between", value1, value2, "collecttime");
            return (Criteria) this;
        }

        public Criteria andCollecttimeNotBetween(Integer value1, Integer value2) {
            addCriterion("collectTime not between", value1, value2, "collecttime");
            return (Criteria) this;
        }

        public Criteria andReadtimeIsNull() {
            addCriterion("readTime is null");
            return (Criteria) this;
        }

        public Criteria andReadtimeIsNotNull() {
            addCriterion("readTime is not null");
            return (Criteria) this;
        }

        public Criteria andReadtimeEqualTo(Integer value) {
            addCriterion("readTime =", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeNotEqualTo(Integer value) {
            addCriterion("readTime <>", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeGreaterThan(Integer value) {
            addCriterion("readTime >", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("readTime >=", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeLessThan(Integer value) {
            addCriterion("readTime <", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeLessThanOrEqualTo(Integer value) {
            addCriterion("readTime <=", value, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeIn(List<Integer> values) {
            addCriterion("readTime in", values, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeNotIn(List<Integer> values) {
            addCriterion("readTime not in", values, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeBetween(Integer value1, Integer value2) {
            addCriterion("readTime between", value1, value2, "readtime");
            return (Criteria) this;
        }

        public Criteria andReadtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("readTime not between", value1, value2, "readtime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIsNull() {
            addCriterion("praiseTime is null");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIsNotNull() {
            addCriterion("praiseTime is not null");
            return (Criteria) this;
        }

        public Criteria andPraisetimeEqualTo(Integer value) {
            addCriterion("praiseTime =", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotEqualTo(Integer value) {
            addCriterion("praiseTime <>", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeGreaterThan(Integer value) {
            addCriterion("praiseTime >", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("praiseTime >=", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeLessThan(Integer value) {
            addCriterion("praiseTime <", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeLessThanOrEqualTo(Integer value) {
            addCriterion("praiseTime <=", value, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeIn(List<Integer> values) {
            addCriterion("praiseTime in", values, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotIn(List<Integer> values) {
            addCriterion("praiseTime not in", values, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeBetween(Integer value1, Integer value2) {
            addCriterion("praiseTime between", value1, value2, "praisetime");
            return (Criteria) this;
        }

        public Criteria andPraisetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("praiseTime not between", value1, value2, "praisetime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeIsNull() {
            addCriterion("complaintTime is null");
            return (Criteria) this;
        }

        public Criteria andComplainttimeIsNotNull() {
            addCriterion("complaintTime is not null");
            return (Criteria) this;
        }

        public Criteria andComplainttimeEqualTo(Integer value) {
            addCriterion("complaintTime =", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeNotEqualTo(Integer value) {
            addCriterion("complaintTime <>", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeGreaterThan(Integer value) {
            addCriterion("complaintTime >", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("complaintTime >=", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeLessThan(Integer value) {
            addCriterion("complaintTime <", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeLessThanOrEqualTo(Integer value) {
            addCriterion("complaintTime <=", value, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeIn(List<Integer> values) {
            addCriterion("complaintTime in", values, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeNotIn(List<Integer> values) {
            addCriterion("complaintTime not in", values, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeBetween(Integer value1, Integer value2) {
            addCriterion("complaintTime between", value1, value2, "complainttime");
            return (Criteria) this;
        }

        public Criteria andComplainttimeNotBetween(Integer value1, Integer value2) {
            addCriterion("complaintTime not between", value1, value2, "complainttime");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlIsNull() {
            addCriterion("microblogUrl is null");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlIsNotNull() {
            addCriterion("microblogUrl is not null");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlEqualTo(String value) {
            addCriterion("microblogUrl =", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlNotEqualTo(String value) {
            addCriterion("microblogUrl <>", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlGreaterThan(String value) {
            addCriterion("microblogUrl >", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlGreaterThanOrEqualTo(String value) {
            addCriterion("microblogUrl >=", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlLessThan(String value) {
            addCriterion("microblogUrl <", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlLessThanOrEqualTo(String value) {
            addCriterion("microblogUrl <=", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlLike(String value) {
            addCriterion("microblogUrl like", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlNotLike(String value) {
            addCriterion("microblogUrl not like", value, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlIn(List<String> values) {
            addCriterion("microblogUrl in", values, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlNotIn(List<String> values) {
            addCriterion("microblogUrl not in", values, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlBetween(String value1, String value2) {
            addCriterion("microblogUrl between", value1, value2, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andMicroblogurlNotBetween(String value1, String value2) {
            addCriterion("microblogUrl not between", value1, value2, "microblogurl");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table microbloginfo_
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table microbloginfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}