package com.project.model;

public class QuesScenicRelationData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quesscenrelation_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quesscenrelation_.scenicid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long scenicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quesscenrelation_.questionID
     *
     * @return the value of quesscenrelation_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quesscenrelation_.questionID
     *
     * @param questionid the value for quesscenrelation_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quesscenrelation_.scenicid
     *
     * @return the value of quesscenrelation_.scenicid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quesscenrelation_.scenicid
     *
     * @param scenicid the value for quesscenrelation_.scenicid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }
}