package com.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestionDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public QuestionDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionidIsNull() {
            addCriterion("questionID is null");
            return (Criteria) this;
        }

        public Criteria andQuestionidIsNotNull() {
            addCriterion("questionID is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionidEqualTo(Long value) {
            addCriterion("questionID =", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotEqualTo(Long value) {
            addCriterion("questionID <>", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThan(Long value) {
            addCriterion("questionID >", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidGreaterThanOrEqualTo(Long value) {
            addCriterion("questionID >=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThan(Long value) {
            addCriterion("questionID <", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidLessThanOrEqualTo(Long value) {
            addCriterion("questionID <=", value, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidIn(List<Long> values) {
            addCriterion("questionID in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotIn(List<Long> values) {
            addCriterion("questionID not in", values, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidBetween(Long value1, Long value2) {
            addCriterion("questionID between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andQuestionidNotBetween(Long value1, Long value2) {
            addCriterion("questionID not between", value1, value2, "questionid");
            return (Criteria) this;
        }

        public Criteria andAskidIsNull() {
            addCriterion("askID is null");
            return (Criteria) this;
        }

        public Criteria andAskidIsNotNull() {
            addCriterion("askID is not null");
            return (Criteria) this;
        }

        public Criteria andAskidEqualTo(Long value) {
            addCriterion("askID =", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidNotEqualTo(Long value) {
            addCriterion("askID <>", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidGreaterThan(Long value) {
            addCriterion("askID >", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidGreaterThanOrEqualTo(Long value) {
            addCriterion("askID >=", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidLessThan(Long value) {
            addCriterion("askID <", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidLessThanOrEqualTo(Long value) {
            addCriterion("askID <=", value, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidIn(List<Long> values) {
            addCriterion("askID in", values, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidNotIn(List<Long> values) {
            addCriterion("askID not in", values, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidBetween(Long value1, Long value2) {
            addCriterion("askID between", value1, value2, "askid");
            return (Criteria) this;
        }

        public Criteria andAskidNotBetween(Long value1, Long value2) {
            addCriterion("askID not between", value1, value2, "askid");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleIsNull() {
            addCriterion("questionTitle is null");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleIsNotNull() {
            addCriterion("questionTitle is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleEqualTo(String value) {
            addCriterion("questionTitle =", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleNotEqualTo(String value) {
            addCriterion("questionTitle <>", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleGreaterThan(String value) {
            addCriterion("questionTitle >", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleGreaterThanOrEqualTo(String value) {
            addCriterion("questionTitle >=", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleLessThan(String value) {
            addCriterion("questionTitle <", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleLessThanOrEqualTo(String value) {
            addCriterion("questionTitle <=", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleLike(String value) {
            addCriterion("questionTitle like", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleNotLike(String value) {
            addCriterion("questionTitle not like", value, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleIn(List<String> values) {
            addCriterion("questionTitle in", values, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleNotIn(List<String> values) {
            addCriterion("questionTitle not in", values, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleBetween(String value1, String value2) {
            addCriterion("questionTitle between", value1, value2, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontitleNotBetween(String value1, String value2) {
            addCriterion("questionTitle not between", value1, value2, "questiontitle");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidIsNull() {
            addCriterion("questionTagID is null");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidIsNotNull() {
            addCriterion("questionTagID is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidEqualTo(Long value) {
            addCriterion("questionTagID =", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidNotEqualTo(Long value) {
            addCriterion("questionTagID <>", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidGreaterThan(Long value) {
            addCriterion("questionTagID >", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidGreaterThanOrEqualTo(Long value) {
            addCriterion("questionTagID >=", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidLessThan(Long value) {
            addCriterion("questionTagID <", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidLessThanOrEqualTo(Long value) {
            addCriterion("questionTagID <=", value, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidIn(List<Long> values) {
            addCriterion("questionTagID in", values, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidNotIn(List<Long> values) {
            addCriterion("questionTagID not in", values, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidBetween(Long value1, Long value2) {
            addCriterion("questionTagID between", value1, value2, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiontagidNotBetween(Long value1, Long value2) {
            addCriterion("questionTagID not between", value1, value2, "questiontagid");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionIsNull() {
            addCriterion("questionDiscription is null");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionIsNotNull() {
            addCriterion("questionDiscription is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionEqualTo(String value) {
            addCriterion("questionDiscription =", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionNotEqualTo(String value) {
            addCriterion("questionDiscription <>", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionGreaterThan(String value) {
            addCriterion("questionDiscription >", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionGreaterThanOrEqualTo(String value) {
            addCriterion("questionDiscription >=", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionLessThan(String value) {
            addCriterion("questionDiscription <", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionLessThanOrEqualTo(String value) {
            addCriterion("questionDiscription <=", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionLike(String value) {
            addCriterion("questionDiscription like", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionNotLike(String value) {
            addCriterion("questionDiscription not like", value, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionIn(List<String> values) {
            addCriterion("questionDiscription in", values, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionNotIn(List<String> values) {
            addCriterion("questionDiscription not in", values, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionBetween(String value1, String value2) {
            addCriterion("questionDiscription between", value1, value2, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondiscriptionNotBetween(String value1, String value2) {
            addCriterion("questionDiscription not between", value1, value2, "questiondiscription");
            return (Criteria) this;
        }

        public Criteria andQuestiondateIsNull() {
            addCriterion("questionDate is null");
            return (Criteria) this;
        }

        public Criteria andQuestiondateIsNotNull() {
            addCriterion("questionDate is not null");
            return (Criteria) this;
        }

        public Criteria andQuestiondateEqualTo(Date value) {
            addCriterion("questionDate =", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateNotEqualTo(Date value) {
            addCriterion("questionDate <>", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateGreaterThan(Date value) {
            addCriterion("questionDate >", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateGreaterThanOrEqualTo(Date value) {
            addCriterion("questionDate >=", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateLessThan(Date value) {
            addCriterion("questionDate <", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateLessThanOrEqualTo(Date value) {
            addCriterion("questionDate <=", value, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateIn(List<Date> values) {
            addCriterion("questionDate in", values, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateNotIn(List<Date> values) {
            addCriterion("questionDate not in", values, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateBetween(Date value1, Date value2) {
            addCriterion("questionDate between", value1, value2, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestiondateNotBetween(Date value1, Date value2) {
            addCriterion("questionDate not between", value1, value2, "questiondate");
            return (Criteria) this;
        }

        public Criteria andQuestionpvIsNull() {
            addCriterion("questionPV is null");
            return (Criteria) this;
        }

        public Criteria andQuestionpvIsNotNull() {
            addCriterion("questionPV is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionpvEqualTo(Integer value) {
            addCriterion("questionPV =", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvNotEqualTo(Integer value) {
            addCriterion("questionPV <>", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvGreaterThan(Integer value) {
            addCriterion("questionPV >", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionPV >=", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvLessThan(Integer value) {
            addCriterion("questionPV <", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvLessThanOrEqualTo(Integer value) {
            addCriterion("questionPV <=", value, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvIn(List<Integer> values) {
            addCriterion("questionPV in", values, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvNotIn(List<Integer> values) {
            addCriterion("questionPV not in", values, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvBetween(Integer value1, Integer value2) {
            addCriterion("questionPV between", value1, value2, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionpvNotBetween(Integer value1, Integer value2) {
            addCriterion("questionPV not between", value1, value2, "questionpv");
            return (Criteria) this;
        }

        public Criteria andQuestionurlIsNull() {
            addCriterion("questionUrl is null");
            return (Criteria) this;
        }

        public Criteria andQuestionurlIsNotNull() {
            addCriterion("questionUrl is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionurlEqualTo(String value) {
            addCriterion("questionUrl =", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlNotEqualTo(String value) {
            addCriterion("questionUrl <>", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlGreaterThan(String value) {
            addCriterion("questionUrl >", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlGreaterThanOrEqualTo(String value) {
            addCriterion("questionUrl >=", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlLessThan(String value) {
            addCriterion("questionUrl <", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlLessThanOrEqualTo(String value) {
            addCriterion("questionUrl <=", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlLike(String value) {
            addCriterion("questionUrl like", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlNotLike(String value) {
            addCriterion("questionUrl not like", value, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlIn(List<String> values) {
            addCriterion("questionUrl in", values, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlNotIn(List<String> values) {
            addCriterion("questionUrl not in", values, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlBetween(String value1, String value2) {
            addCriterion("questionUrl between", value1, value2, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionurlNotBetween(String value1, String value2) {
            addCriterion("questionUrl not between", value1, value2, "questionurl");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvIsNull() {
            addCriterion("questionValidPV is null");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvIsNotNull() {
            addCriterion("questionValidPV is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvEqualTo(Integer value) {
            addCriterion("questionValidPV =", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvNotEqualTo(Integer value) {
            addCriterion("questionValidPV <>", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvGreaterThan(Integer value) {
            addCriterion("questionValidPV >", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionValidPV >=", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvLessThan(Integer value) {
            addCriterion("questionValidPV <", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvLessThanOrEqualTo(Integer value) {
            addCriterion("questionValidPV <=", value, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvIn(List<Integer> values) {
            addCriterion("questionValidPV in", values, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvNotIn(List<Integer> values) {
            addCriterion("questionValidPV not in", values, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvBetween(Integer value1, Integer value2) {
            addCriterion("questionValidPV between", value1, value2, "questionvalidpv");
            return (Criteria) this;
        }

        public Criteria andQuestionvalidpvNotBetween(Integer value1, Integer value2) {
            addCriterion("questionValidPV not between", value1, value2, "questionvalidpv");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioninfo_
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioninfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}