package com.project.model;

import java.util.Date;

public class QuestionData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.askID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long askid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionTitle
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String questiontitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionTagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long questiontagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionDiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String questiondiscription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionDate
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Date questiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer questionpv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String questionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioninfo_.questionValidPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer questionvalidpv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionID
     *
     * @return the value of questioninfo_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionID
     *
     * @param questionid the value for questioninfo_.questionID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionid(Long questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.askID
     *
     * @return the value of questioninfo_.askID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getAskid() {
        return askid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.askID
     *
     * @param askid the value for questioninfo_.askID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAskid(Long askid) {
        this.askid = askid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionTitle
     *
     * @return the value of questioninfo_.questionTitle
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getQuestiontitle() {
        return questiontitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionTitle
     *
     * @param questiontitle the value for questioninfo_.questionTitle
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestiontitle(String questiontitle) {
        this.questiontitle = questiontitle == null ? null : questiontitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionTagID
     *
     * @return the value of questioninfo_.questionTagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getQuestiontagid() {
        return questiontagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionTagID
     *
     * @param questiontagid the value for questioninfo_.questionTagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestiontagid(Long questiontagid) {
        this.questiontagid = questiontagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionDiscription
     *
     * @return the value of questioninfo_.questionDiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getQuestiondiscription() {
        return questiondiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionDiscription
     *
     * @param questiondiscription the value for questioninfo_.questionDiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestiondiscription(String questiondiscription) {
        this.questiondiscription = questiondiscription == null ? null : questiondiscription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionDate
     *
     * @return the value of questioninfo_.questionDate
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Date getQuestiondate() {
        return questiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionDate
     *
     * @param questiondate the value for questioninfo_.questionDate
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestiondate(Date questiondate) {
        this.questiondate = questiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionPV
     *
     * @return the value of questioninfo_.questionPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getQuestionpv() {
        return questionpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionPV
     *
     * @param questionpv the value for questioninfo_.questionPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionpv(Integer questionpv) {
        this.questionpv = questionpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionUrl
     *
     * @return the value of questioninfo_.questionUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getQuestionurl() {
        return questionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionUrl
     *
     * @param questionurl the value for questioninfo_.questionUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionurl(String questionurl) {
        this.questionurl = questionurl == null ? null : questionurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioninfo_.questionValidPV
     *
     * @return the value of questioninfo_.questionValidPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getQuestionvalidpv() {
        return questionvalidpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioninfo_.questionValidPV
     *
     * @param questionvalidpv the value for questioninfo_.questionValidPV
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQuestionvalidpv(Integer questionvalidpv) {
        this.questionvalidpv = questionvalidpv;
    }
}