package com.project.model;

public class RelateScenicData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relatescenicinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long relatescenicid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relatescenicinfo_.RelateScenicID
     *
     * @return the value of relatescenicinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getRelatescenicid() {
        return relatescenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relatescenicinfo_.RelateScenicID
     *
     * @param relatescenicid the value for relatescenicinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setRelatescenicid(Long relatescenicid) {
        this.relatescenicid = relatescenicid;
    }
}