package com.project.model;

public class ScenicCollectData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sceniccollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sceniccollect_.sceniccollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long sceniccollect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sceniccollect_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sceniccollect_.id
     *
     * @return the value of sceniccollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sceniccollect_.id
     *
     * @param id the value for sceniccollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sceniccollect_.sceniccollect
     *
     * @return the value of sceniccollect_.sceniccollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getSceniccollect() {
        return sceniccollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sceniccollect_.sceniccollect
     *
     * @param sceniccollect the value for sceniccollect_.sceniccollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setSceniccollect(Long sceniccollect) {
        this.sceniccollect = sceniccollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sceniccollect_.userid
     *
     * @return the value of sceniccollect_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sceniccollect_.userid
     *
     * @param userid the value for sceniccollect_.userid
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}