package com.project.model;

public class ScenicData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.food
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float food;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.nice
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float nice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.traffic
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float traffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.cultural
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float cultural;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.recommend
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.totalScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Float totalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.gradeNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer gradenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.vpNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer vpnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicSurroundInfoID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer scenicsurroundinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String scenicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.validVPNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long validvpnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicID
     *
     * @return the value of scenicinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicID
     *
     * @param scenicid the value for scenicinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.food
     *
     * @return the value of scenicinfo_.food
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getFood() {
        return food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.food
     *
     * @param food the value for scenicinfo_.food
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setFood(Float food) {
        this.food = food;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.nice
     *
     * @return the value of scenicinfo_.nice
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getNice() {
        return nice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.nice
     *
     * @param nice the value for scenicinfo_.nice
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setNice(Float nice) {
        this.nice = nice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.traffic
     *
     * @return the value of scenicinfo_.traffic
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.traffic
     *
     * @param traffic the value for scenicinfo_.traffic
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTraffic(Float traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.cultural
     *
     * @return the value of scenicinfo_.cultural
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getCultural() {
        return cultural;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.cultural
     *
     * @param cultural the value for scenicinfo_.cultural
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCultural(Float cultural) {
        this.cultural = cultural;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.recommend
     *
     * @return the value of scenicinfo_.recommend
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.recommend
     *
     * @param recommend the value for scenicinfo_.recommend
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setRecommend(Float recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.totalScore
     *
     * @return the value of scenicinfo_.totalScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Float getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.totalScore
     *
     * @param totalscore the value for scenicinfo_.totalScore
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTotalscore(Float totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.gradeNumber
     *
     * @return the value of scenicinfo_.gradeNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getGradenumber() {
        return gradenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.gradeNumber
     *
     * @param gradenumber the value for scenicinfo_.gradeNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setGradenumber(Integer gradenumber) {
        this.gradenumber = gradenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.vpNumber
     *
     * @return the value of scenicinfo_.vpNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getVpnumber() {
        return vpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.vpNumber
     *
     * @param vpnumber the value for scenicinfo_.vpNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setVpnumber(Integer vpnumber) {
        this.vpnumber = vpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicSurroundInfoID
     *
     * @return the value of scenicinfo_.scenicSurroundInfoID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getScenicsurroundinfoid() {
        return scenicsurroundinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicSurroundInfoID
     *
     * @param scenicsurroundinfoid the value for scenicinfo_.scenicSurroundInfoID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicsurroundinfoid(Integer scenicsurroundinfoid) {
        this.scenicsurroundinfoid = scenicsurroundinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicUrl
     *
     * @return the value of scenicinfo_.scenicUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getScenicurl() {
        return scenicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicUrl
     *
     * @param scenicurl the value for scenicinfo_.scenicUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicurl(String scenicurl) {
        this.scenicurl = scenicurl == null ? null : scenicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.validVPNumber
     *
     * @return the value of scenicinfo_.validVPNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getValidvpnumber() {
        return validvpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.validVPNumber
     *
     * @param validvpnumber the value for scenicinfo_.validVPNumber
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setValidvpnumber(Long validvpnumber) {
        this.validvpnumber = validvpnumber;
    }
}