package com.project.model;

public class TagData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taginfo_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taginfo_.tagname
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String tagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taginfo_.tagdiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String tagdiscription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taginfo_.tagID
     *
     * @return the value of taginfo_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taginfo_.tagID
     *
     * @param tagid the value for taginfo_.tagID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTagid(Long tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taginfo_.tagname
     *
     * @return the value of taginfo_.tagname
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taginfo_.tagname
     *
     * @param tagname the value for taginfo_.tagname
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taginfo_.tagdiscription
     *
     * @return the value of taginfo_.tagdiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getTagdiscription() {
        return tagdiscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taginfo_.tagdiscription
     *
     * @param tagdiscription the value for taginfo_.tagdiscription
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTagdiscription(String tagdiscription) {
        this.tagdiscription = tagdiscription == null ? null : tagdiscription.trim();
    }
}