package com.project.model;

import java.util.Date;

public class TravelnoteData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long travelnoteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long scenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.contextDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String contextdir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer collecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer readtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer praisetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer relatescenicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer complainttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String microblogurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnoteinfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.travelnoteID
     *
     * @return the value of travelnoteinfo_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getTravelnoteid() {
        return travelnoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.travelnoteID
     *
     * @param travelnoteid the value for travelnoteinfo_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTravelnoteid(Long travelnoteid) {
        this.travelnoteid = travelnoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.authorID
     *
     * @return the value of travelnoteinfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.authorID
     *
     * @param authorid the value for travelnoteinfo_.authorID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setAuthorid(Long authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.scenicID
     *
     * @return the value of travelnoteinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.scenicID
     *
     * @param scenicid the value for travelnoteinfo_.scenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.publishTime
     *
     * @return the value of travelnoteinfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.publishTime
     *
     * @param publishtime the value for travelnoteinfo_.publishTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.contextDir
     *
     * @return the value of travelnoteinfo_.contextDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getContextdir() {
        return contextdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.contextDir
     *
     * @param contextdir the value for travelnoteinfo_.contextDir
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setContextdir(String contextdir) {
        this.contextdir = contextdir == null ? null : contextdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.collectTime
     *
     * @return the value of travelnoteinfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getCollecttime() {
        return collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.collectTime
     *
     * @param collecttime the value for travelnoteinfo_.collectTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setCollecttime(Integer collecttime) {
        this.collecttime = collecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.readTime
     *
     * @return the value of travelnoteinfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.readTime
     *
     * @param readtime the value for travelnoteinfo_.readTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setReadtime(Integer readtime) {
        this.readtime = readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.praiseTime
     *
     * @return the value of travelnoteinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getPraisetime() {
        return praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.praiseTime
     *
     * @param praisetime the value for travelnoteinfo_.praiseTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setPraisetime(Integer praisetime) {
        this.praisetime = praisetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.RelateScenicID
     *
     * @return the value of travelnoteinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getRelatescenicid() {
        return relatescenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.RelateScenicID
     *
     * @param relatescenicid the value for travelnoteinfo_.RelateScenicID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setRelatescenicid(Integer relatescenicid) {
        this.relatescenicid = relatescenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.complaintTime
     *
     * @return the value of travelnoteinfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getComplainttime() {
        return complainttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.complaintTime
     *
     * @param complainttime the value for travelnoteinfo_.complaintTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setComplainttime(Integer complainttime) {
        this.complainttime = complainttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.microblogUrl
     *
     * @return the value of travelnoteinfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getMicroblogurl() {
        return microblogurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.microblogUrl
     *
     * @param microblogurl the value for travelnoteinfo_.microblogUrl
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setMicroblogurl(String microblogurl) {
        this.microblogurl = microblogurl == null ? null : microblogurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnoteinfo_.state
     *
     * @return the value of travelnoteinfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnoteinfo_.state
     *
     * @param state the value for travelnoteinfo_.state
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}