package com.project.model;

public class TravelnoteCollectData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnotecollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnotecollect_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long travelnoteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travelnotecollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnotecollect_.id
     *
     * @return the value of travelnotecollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnotecollect_.id
     *
     * @param id the value for travelnotecollect_.id
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnotecollect_.travelnoteID
     *
     * @return the value of travelnotecollect_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getTravelnoteid() {
        return travelnoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnotecollect_.travelnoteID
     *
     * @param travelnoteid the value for travelnotecollect_.travelnoteID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTravelnoteid(Long travelnoteid) {
        this.travelnoteid = travelnoteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travelnotecollect_.userID
     *
     * @return the value of travelnotecollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travelnotecollect_.userID
     *
     * @param userid the value for travelnotecollect_.userID
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }
}