package com.project.model;

public class ValidAccessionData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column validaccessinfo_.visitTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer visittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column validaccessinfo_.travelnoteTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer travelnotetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column validaccessinfo_.qaATime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer qaatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column validaccessinfo_.isCollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    private Integer iscollect;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column validaccessinfo_.visitTime
     *
     * @return the value of validaccessinfo_.visitTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getVisittime() {
        return visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column validaccessinfo_.visitTime
     *
     * @param visittime the value for validaccessinfo_.visitTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setVisittime(Integer visittime) {
        this.visittime = visittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column validaccessinfo_.travelnoteTime
     *
     * @return the value of validaccessinfo_.travelnoteTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getTravelnotetime() {
        return travelnotetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column validaccessinfo_.travelnoteTime
     *
     * @param travelnotetime the value for validaccessinfo_.travelnoteTime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setTravelnotetime(Integer travelnotetime) {
        this.travelnotetime = travelnotetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column validaccessinfo_.qaATime
     *
     * @return the value of validaccessinfo_.qaATime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getQaatime() {
        return qaatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column validaccessinfo_.qaATime
     *
     * @param qaatime the value for validaccessinfo_.qaATime
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setQaatime(Integer qaatime) {
        this.qaatime = qaatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column validaccessinfo_.isCollect
     *
     * @return the value of validaccessinfo_.isCollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Integer getIscollect() {
        return iscollect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column validaccessinfo_.isCollect
     *
     * @param iscollect the value for validaccessinfo_.isCollect
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setIscollect(Integer iscollect) {
        this.iscollect = iscollect;
    }
}