package com.project.model;

import java.util.ArrayList;
import java.util.List;

public class ValidAccessionDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public ValidAccessionDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVisittimeIsNull() {
            addCriterion("visitTime is null");
            return (Criteria) this;
        }

        public Criteria andVisittimeIsNotNull() {
            addCriterion("visitTime is not null");
            return (Criteria) this;
        }

        public Criteria andVisittimeEqualTo(Integer value) {
            addCriterion("visitTime =", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeNotEqualTo(Integer value) {
            addCriterion("visitTime <>", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeGreaterThan(Integer value) {
            addCriterion("visitTime >", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("visitTime >=", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeLessThan(Integer value) {
            addCriterion("visitTime <", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeLessThanOrEqualTo(Integer value) {
            addCriterion("visitTime <=", value, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeIn(List<Integer> values) {
            addCriterion("visitTime in", values, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeNotIn(List<Integer> values) {
            addCriterion("visitTime not in", values, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeBetween(Integer value1, Integer value2) {
            addCriterion("visitTime between", value1, value2, "visittime");
            return (Criteria) this;
        }

        public Criteria andVisittimeNotBetween(Integer value1, Integer value2) {
            addCriterion("visitTime not between", value1, value2, "visittime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeIsNull() {
            addCriterion("travelnoteTime is null");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeIsNotNull() {
            addCriterion("travelnoteTime is not null");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeEqualTo(Integer value) {
            addCriterion("travelnoteTime =", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeNotEqualTo(Integer value) {
            addCriterion("travelnoteTime <>", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeGreaterThan(Integer value) {
            addCriterion("travelnoteTime >", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("travelnoteTime >=", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeLessThan(Integer value) {
            addCriterion("travelnoteTime <", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeLessThanOrEqualTo(Integer value) {
            addCriterion("travelnoteTime <=", value, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeIn(List<Integer> values) {
            addCriterion("travelnoteTime in", values, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeNotIn(List<Integer> values) {
            addCriterion("travelnoteTime not in", values, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeBetween(Integer value1, Integer value2) {
            addCriterion("travelnoteTime between", value1, value2, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andTravelnotetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("travelnoteTime not between", value1, value2, "travelnotetime");
            return (Criteria) this;
        }

        public Criteria andQaatimeIsNull() {
            addCriterion("qaATime is null");
            return (Criteria) this;
        }

        public Criteria andQaatimeIsNotNull() {
            addCriterion("qaATime is not null");
            return (Criteria) this;
        }

        public Criteria andQaatimeEqualTo(Integer value) {
            addCriterion("qaATime =", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeNotEqualTo(Integer value) {
            addCriterion("qaATime <>", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeGreaterThan(Integer value) {
            addCriterion("qaATime >", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("qaATime >=", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeLessThan(Integer value) {
            addCriterion("qaATime <", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeLessThanOrEqualTo(Integer value) {
            addCriterion("qaATime <=", value, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeIn(List<Integer> values) {
            addCriterion("qaATime in", values, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeNotIn(List<Integer> values) {
            addCriterion("qaATime not in", values, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeBetween(Integer value1, Integer value2) {
            addCriterion("qaATime between", value1, value2, "qaatime");
            return (Criteria) this;
        }

        public Criteria andQaatimeNotBetween(Integer value1, Integer value2) {
            addCriterion("qaATime not between", value1, value2, "qaatime");
            return (Criteria) this;
        }

        public Criteria andIscollectIsNull() {
            addCriterion("isCollect is null");
            return (Criteria) this;
        }

        public Criteria andIscollectIsNotNull() {
            addCriterion("isCollect is not null");
            return (Criteria) this;
        }

        public Criteria andIscollectEqualTo(Integer value) {
            addCriterion("isCollect =", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectNotEqualTo(Integer value) {
            addCriterion("isCollect <>", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectGreaterThan(Integer value) {
            addCriterion("isCollect >", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectGreaterThanOrEqualTo(Integer value) {
            addCriterion("isCollect >=", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectLessThan(Integer value) {
            addCriterion("isCollect <", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectLessThanOrEqualTo(Integer value) {
            addCriterion("isCollect <=", value, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectIn(List<Integer> values) {
            addCriterion("isCollect in", values, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectNotIn(List<Integer> values) {
            addCriterion("isCollect not in", values, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectBetween(Integer value1, Integer value2) {
            addCriterion("isCollect between", value1, value2, "iscollect");
            return (Criteria) this;
        }

        public Criteria andIscollectNotBetween(Integer value1, Integer value2) {
            addCriterion("isCollect not between", value1, value2, "iscollect");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validaccessinfo_
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table validaccessinfo_
     *
     * @mbggenerated Fri Sep 08 10:01:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}